# ----------------------------------------
# Created on: Sat Nov 11 16:23:51 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/23600/Desktop/full_screen/sim/usim"
vmap  adc "C:/Users/23600/Desktop/full_screen/sim/adc"
vmap  ddrc "C:/Users/23600/Desktop/full_screen/sim/ddrc"
vmap  ddrphy "C:/Users/23600/Desktop/full_screen/sim/ddrphy"
vmap  hsst_e2 "C:/Users/23600/Desktop/full_screen/sim/hsst_e2"
vmap  iolhr_dft "C:/Users/23600/Desktop/full_screen/sim/iolhr_dft"
vmap  ipal_e1 "C:/Users/23600/Desktop/full_screen/sim/ipal_e1"
vmap  pciegen2 "C:/Users/23600/Desktop/full_screen/sim/pciegen2"
vlog   "C:/Users/23600/Desktop/full_screen/source/ddr_arbit.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/frame_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/cmos_8_16bit.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/i2c_com.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/iic_dri.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/ms72xx_ctl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/ms7200_ctl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/ms7210_ctl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/power_on_delay.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/rd_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/reg_config.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/sync_vg.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/wr_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/rd_ctrl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/wr_cmd_trans.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/wr_ctrl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rtl/wr_rd_ctrl_top.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/image_size_down_without_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/calculator.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/ram_fifo_ctrl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/rfifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/scaler.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/calculator_3.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/scaler_3.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/calculator_2.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/scaler_2.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/calculator_4.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale/scaler_4.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/key_config.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/mul_2_8/rtl/ipml_mult_v1_2_mul_2_8.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/mul_2_8/mul_2_8.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/wr_fram_buf/rtl/ipml_sdpram_v1_6_wr_fram_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/wr_fram_buf/wr_fram_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rd_fram_buf/rtl/ipml_sdpram_v1_6_rd_fram_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/rd_fram_buf/rd_fram_buf.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/ipcore/pll/pll.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/size_down_fifo/rtl/ipm_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/size_down_fifo/rtl/ipm_distributed_fifo_v1_2_size_down_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/size_down_fifo/rtl/ipm_distributed_sdpram_v1_2_size_down_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/size_down_fifo/size_down_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale_fifo/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale_fifo/rtl/ipml_sdpram_v1_6_scale_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale_fifo/rtl/ipml_fifo_v1_6_scale_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/scale_fifo/scale_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/ram_fifo/rtl/ipml_sdpram_v1_6_ram_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/ram_fifo/ram_fifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/x_scale_rom/rtl/ipml_rom_v1_5_x_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/x_scale_rom/rtl/ipml_spram_v1_5_x_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/x_scale_rom/x_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/y_scale_rom/rtl/ipml_rom_v1_5_y_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/y_scale_rom/rtl/ipml_spram_v1_5_y_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/ipcore/y_scale_rom/y_scale_rom.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/sim/tb_ram_fifo_ctrl.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/sim/tb_rfifo.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/sim/tb_imgae_size_down.v" -work work
vlog   "C:/Users/23600/Desktop/full_screen/source/tb_key_config.v" -work work

# ----------------------------------------
